# Generated by Django 4.1 on 2022-10-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='grado',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
