# Generated by Django 4.1 on 2022-09-06 23:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_productlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('products_id', 'users_id')},
        ),
    ]
