# Generated by Django 4.1 on 2022-09-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productlike_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(null=True, upload_to='products/images/'),
        ),
    ]
